### ISSUE TITLE
npm run build fails: sponge missing

### ISSUE THREAD

**Issue by dancesWithCycles** [derhuerst/berlin-gtfs-rt-server#5]
Hi there,
According to this [line](https://github.com/derhuerst/berlin-gtfs-rt-server/blob/18a61a38f0031e6dc701ab36e176323b07b273d2/readme.md?plain=1#L35) I called this instruction

```shell
npm run build
```

, that came back with this reply.

```
npm run build

> berlin-gtfs-rt-server@4.0.0 build
> ./build.sh && npm run docs

+ grep '^PG'
PGPORT=<secret>
PGPASSWORD=<secret>
PGUSER=<secret>
PGDATABASE=<secret>
PGHOST=<secret>
+ NODE_ENV=production
+ node_modules/.bin/gtfs-to-sql -d --trips-without-shape-id --routes-without-agency-id -- gtfs/agency.csv gtfs/calendar.csv gtfs/calendar_dates.csv gtfs/frequencies.csv gtfs/routes.csv gtfs/stop_times.csv gtfs/stops.csv gtfs/transfers.csv gtfs/trips.csv
+ psql -b
+ sponge
./build.sh: line 24: sponge: command not found
PostGraphile PostgreSQL user's password: <secret>
PostrREST PostgreSQL user's password: <secret>
```

I am wondering about this

```
./build.sh: line 24: sponge: command not found
```

and this

```
PostGraphile PostgreSQL user's password: <secret>
PostrREST PostgreSQL user's password: <secret>
```

snippet. Any hint why `sponge` is not found and the GTFS feed is not imported into PostgreSQL?

Cheers!

**Comment by derhuerst** [comment]
Thanks for reporting this!

The "prerequisites" section of the readme doesn't mention that [`sponge`](https://linux.die.net/man/1/sponge) from [`moreutils`](https://repology.org/project/moreutils/information) needs to be installed.

**Comment by dancesWithCycles** [comment]
You are very welcome!

Do you want do make this repository available to more people? The ```sponge``` command line instruction is not a standard tool and this way not available for anyone. I could imagine to substitute ```sponge``` with ```tee``` or with ```tee "$@" > /dev/null``` when you mind the pipe to standard output or even  substitute ```sponge``` with a shell function ```my-sponge``` passing the data through a temporary file. What do you think?

**Comment by derhuerst** [comment]
I introduced the `sponge` call in https://github.com/derhuerst/berlin-gtfs-rt-server/commit/1b9be1f2df5c0f34a0c1d4985a5552b3d039299c. The build had failed randomly (SQL syntax errors, weirdly enough 🤔), and I still don't know what the actually reason is.

But `sponge` buffers the entire SQL before it is read by `psql`, which circumvents the problem. Does `tee` actually do the same?

And: Is `tee` preinstalled on all platforms? Because if some users need to install a package *anyways*, then I prefer the tool intended for what I'm trying to achieve.

Defining a custom shell function would solve the issue, but a) I don't want to populate a temporary file, as `berlin-gtfs-rt-server` should work in read-only environments (e.g. containers), and b) I don't want to add more complexity to this repo when an existing tool solves the task cleanly.

**Comment by derhuerst** [comment]
> Do you want do make this repository available to more people? The `sponge` command line instruction is not a standard tool and this way not available for anyone.

True, but I feel like people who can install (or get access to) Git, Node.js, PostgreSQL, PostGIS & `wget` will also be able to install `sponge`. Probably platforms without native package managers (e.g. Windows or macOS) are an exception to this, but I feel like `berlin-gtfs-rt-server` targets a fairly technical audience.

**Comment by derhuerst** [comment]
> ```
> PostGraphile PostgreSQL user's password: <secret>
> PostrREST PostgreSQL user's password: <secret>
> ```

This happens because `gtfs-via-postgres@4` (a dependency of `hafas-gtfs-rt-feed`) [prints the randomly generated passwords](https://github.com/public-transport/gtfs-via-postgres/blob/57da5fde064928207a7c072b61fba1dd46e3b490/index.js#L46-L55) of the `postgraphile` (for [Postgraphile](https://postgraphile.org)) & `postgrest`/`web_anon` (for [PostgREST](https://postgrest.org/)) roles, even if the creation of these roles is disabled. TLDR: This is a bug I should fix in `gtfs-via-postgres`.
